- name: create data mount and folder
  file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
    mode: "0755"
  loop:
    - "{{ data_mount }}"
    - "{{ data_mount }}/postgres"
    - "{{ data_mount }}/redis"
    - "{{ data_mount }}/faraday"

- name: copy docker-compose.yml
  template:
    src: templates/docker-compose.yml.j2
    dest: "{{ compose_dir }}/docker-compose.yml"
    owner: 1000
    group: 1000
    mode: "0644"