- name: create data mount and folder
  file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
    mode: "0755"
  loop:
    - "{{ data_mount }}"
    - "{{ data_mount }}/postgres"
    - "{{ data_mount }}/redis"
    - "{{ data_mount }}/faraday"

- name: render docker-compose.yml
  template:
    src: templates/docker-compose.yml.j2
    dest: "{{ compose_dir }}/docker-compose.yml"
    owner: 1000
    group: 1000
    mode: "0644"
  vars:
    pg_user: "{{ pg_user }}"
    pg_password: "{{ pg_password }}"
    pg_db: "{{ pg_db }}"
    rmq_user: "{{ rmq_user }}"
    rmq_password: "{{ rmq_password }}"

- name: render nginx.conf.j2
  template:
    src: templates/nginx.conf.j2
    dest: "{{ compose_dir }}/nginx.conf"
    owner: 1000
    group: 1000
    mode: "0644"