apiVersion: apps/v1
kind: Deployment
metadata:
  name: faraday
  namespace: "{{TENANT}}"
  labels:
    app: faraday
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faraday
  template:
    metadata:
      labels:
        app: faraday
    spec:
      containers:
        - name: faraday
          image: faradaysec/faraday:latest
          ports:
            - containerPort: 5985
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: faraday
  namespace: "{{TENANT}}"
spec:
  type: ClusterIP
  ports:
    - port: 5985
      targetPort: 5985
  selector:
    app: faraday

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: faraday-hpa
  namespace: "{{TENANT}}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: faraday
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
