apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  namespace: "{{TENANT}}"
  labels:
    app: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
        - name: opa
          image: openpolicyagent/opa:0.54.0
          args: ["run","--server","--addr=0.0.0.0:8181"]
          ports:
            - containerPort: 8181
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: opa
  namespace: "{{TENANT}}"
spec:
  type: ClusterIP
  ports:
    - port: 8181
      targetPort: 8181
  selector:
    app: opa

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: opa-hpa
  namespace: "{{TENANT}}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: opa
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
