apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: "{{TENANT}}"
  labels:
    app: opensearch
spec:
  ports:
    - port: 9200
      name: http
  clusterIP: None
  selector:
    app: opensearch

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
  namespace: "{{TENANT}}"
spec:
  serviceName: opensearch
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2.9.0
          env:
            - name: discovery.type
              value: single-node
            - name: OPENSEARCH_JAVA_OPTS
              value: -Xms512m -Xmx512m
          ports:
            - containerPort: 9200
              name: http
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          volumeMounts:
            - name: data
              mountPath: /usr/share/opensearch/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
