name: Provision Tenant

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      tenant:
        description: 'Tenant ID'
        required: true
        default: 'demo'
      destroy:
        type: boolean
        description: 'Destroy tenant'
        required: false
        default: 'false'

jobs:
  provision-tenant:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        if: ${{ github.event.inputs.destroy != 'true' }}
        env:
          TF_VAR_hetzner_token: ${{ secrets.HETZNER_TOKEN }}
          TF_VAR_cloudflare_token: ${{ secrets.CLOUDFLARE_TOKEN }}
        run: |
          set -e
          # Build terraform -var arguments conditionally from workflow inputs
          ARGS=("-var" "tenant=${{ github.event.inputs.tenant }}")

          terraform apply -target=modules.tenant "${ARGS[@]}" -auto-approve

      - name: Terraform Destroy
        working-directory: ./terraform
        if: ${{ github.event.inputs.destroy == 'true' }}
        env:
          TF_VAR_hetzner_token: ${{ secrets.HETZNER_TOKEN }}
          TF_VAR_cloudflare_token: ${{ secrets.CLOUDFLARE_TOKEN }}
        run: |
          set -e
          terraform destroy -target=modules.tenant -var "tenant=${{ github.event.inputs.tenant }}" -auto-approve

      - name: Upload terraform state (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state-${{ github.event.inputs.tenant }}
          path: terraform/terraform.tfstate

      - name: Commit Terraform state back to repo
        if: always()
        run: |
          set -e
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          BRANCH=${GITHUB_REF#refs/heads/}
          echo "Branch: $BRANCH"
          git add terraform/terraform.tfstate
          if git diff --staged --quiet; then
            echo "No state changes to commit"
          else
            git commit -m "chore(terraform): update state for tenant ${{ github.event.inputs.tenant }} [ci skip]"
            git push origin HEAD:$BRANCH
          fi