name: Provision Tenant
permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      tenant:
        description: 'Tenant id to provision'
        required: true
        default: 'skip'
      quota_hard:
        description: 'Optional ResourceQuota map (HCL map syntax) e.g. {"pods"="20","requests.cpu"="4"}'
        required: false
        default: ''
      limit_default:
        description: 'Optional LimitRange default map (HCL map syntax) e.g. {"cpu"="250m","memory"="512Mi"}'
        required: false
        default: ''

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply (create cluster)
        working-directory: ./terraform
        if: github.event.inputs.tenant != 'skip'
        env:
          TF_VAR_digitalocean_token: ${{ secrets.DIGITALOCEAN_TOKEN }}
        run: |
          set -e
          # Build terraform -var arguments conditionally from workflow inputs
          ARGS=("-var" "tenant=${{ github.event.inputs.tenant }}")

          if [ -n "${{ github.event.inputs.quota_hard }}" ]; then
            ARGS+=("-var" "quota_hard=${{ github.event.inputs.quota_hard }}")
          fi

          if [ -n "${{ github.event.inputs.limit_default }}" ]; then
            ARGS+=("-var" "limit_default=${{ github.event.inputs.limit_default }}")
          fi

          terraform apply "${ARGS[@]}" -auto-approve

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        if: always()
        with:
          version: 'latest'

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        if: always()
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Authenticate doctl (provision job)
        if: always()
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
        run: |
          set -e
          if [ -z "${DIGITALOCEAN_TOKEN:-}" ]; then
            echo "DIGITALOCEAN_TOKEN not set; doctl auth will fail"
          else
            # Ensure doctl is configured for subsequent run steps in this job
            doctl auth init --access-token "$DIGITALOCEAN_TOKEN" >/dev/null 2>&1 || true
            doctl account get || true
          fi

      - name: Save kubeconfig
        if: always()
        run: |
          set -e
          # Capture terraform output and extract a UUID-like cluster id to avoid wrapper/debug noise
          CLUSTER_ID=$(terraform -chdir=terraform output cluster_id 2>/dev/null)
          if [ -z "$CLUSTER_ID" ]; then
            echo "Could not parse cluster_id from terraform output:"
            echo "cluster_id: $CLUSTER_ID"
            exit 0
          fi
          echo "Saving kubeconfig for cluster: $CLUSTER_ID"
          doctl kubernetes cluster kubeconfig save $CLUSTER_ID

      - name: Install cert-manager
        run: |
          # Install cert-manager using kubectl apply (manifest)
          kubectl apply --validate=false -f https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml

      - name: Create Let's Encrypt staging ClusterIssuer
        run: |
          cat <<EOF > cluster-issuer-staging.yaml
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: letsencrypt-staging
          spec:
            acme:
              server: https://acme-staging-v02.api.letsencrypt.org/directory
              email: admin@example.com
              privateKeySecretRef:
                name: letsencrypt-staging
              solvers:
              - http01:
                  ingress:
                    class: nginx
          EOF
          kubectl apply -f cluster-issuer-staging.yaml

      - name: Install NGINX Ingress Controller
        run: |
          # Install a simple nginx ingress (kubernetes/ingress-nginx) via manifest
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml

      - name: Upload terraform state (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state-${{ github.event.inputs.tenant }}
          path: terraform/terraform.tfstate


      - name: Commit Terraform state back to repo
        if: always()
        run: |
          set -e
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          BRANCH=${GITHUB_REF#refs/heads/}
          echo "Branch: $BRANCH"
          git add terraform/terraform.tfstate
          if git diff --staged --quiet; then
            echo "No state changes to commit"
          else
            git commit -m "chore(terraform): update state for tenant ${{ github.event.inputs.tenant }} [ci skip]"
            git push origin HEAD:$BRANCH
          fi